### ISSUE TITLE
Users endpoint selection

### ISSUE THREAD

**Issue by MatthewQualls** [siggame/colisee-api#9]
Endpoints:
- [ ] GetUsers - Matthew
- [ ] GetUser - Matthew
- [ ] CreateUser - Reno
- [ ] UpdateUser - Reno
- [ ] DeleteUser - Reno
- [ ] GetUserTeams
- [ ] GetUserInvites

Utility Functions:
- [ ] _mergeObjs - Matthew

**Comment by renodubois** [comment]
I can go ahead and work on Create/Update/Delete Users
